language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
services:
  - mongodb
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/revel/revel
  - go get -v github.com/revel/cmd/revel
  - go get -v gopkg.in/mgo.v2
  - go get -v gopkg.in/mgo.v2/bson

script:
  - go test github.com/revel/revel

  # Build & run the sample app
  - revel test github.com/janekolszak/revmgo/testapp
